PlaceObj("BuildingTemplate", {
  "name",
  "FastFoodJoint",
  "file_name",
  "FastFoodJoint"
}, {
  PlaceObj("BuildingProperties", {
    "Model",
    "FastFood",
    "Name",
    T({
      5942,
      "Fast-food Joint"
    }),
    "NamePlural",
    T({
      11555,
      "Fast-food Joints"
    }),
    "Description",
    T({
      5943,
      "The Fast-Food Joint serves healthy, slimming food at reasonable prices with minimum waiting time. Everything else you hear is a lie, manufactured by their competitors - the Slow-Food Joint."
    }),
    "MenuText",
    T({
      5944,
      [[
Provides Entertainment for citizens and tourists in the vicinity.

Preferred Tourist Class - Slobs]]
    }),
    "BaseBudgetMin",
    60,
    "BaseBudgetMax",
    120,
    "BasePowerCons",
    20,
    "TourismRatingContribution",
    2,
    "asphalt_road",
    true,
    "TerrainName",
    "square1"
  }),
  PlaceObj("Construction", {
    "Category",
    "attractions",
    "Position",
    12,
    "RequiresDlc",
    "dlc9",
    "ConstructionCost",
    3000,
    "ConstructionPoints",
    180,
    "Era",
    4
  }),
  PlaceObj("Crime", {"BaseAmount", 2}),
  PlaceObj("Pollution", {
    "BaseAmount",
    10,
    "Radius",
    10000
  }),
  PlaceObj("Service", {
    "BaseRadius",
    15000,
    "BaseWealthRequired",
    2,
    "BaseRevenuePer10",
    38,
    "ServiceChildren",
    true,
    "BasePreferSlobs",
    1
  }),
  PlaceObj("StandingComponent", {
    "Type",
    "capitalists",
    "Amount",
    5
  }),
  PlaceObj("Workplace", {
    "BaseMaxWorkers",
    4,
    "BaseInherentWealthProvided",
    2,
    "Manageable",
    true,
    "WorkerProfession",
    "Clerk"
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Home Deliveries",
    "Name",
    T({
      5945,
      "Home Deliveries"
    }),
    "Rollover",
    T({
      5946,
      "Increases Housing Quality of residences in the vicinity by 10 (max 20)."
    }),
    "StartTurnedOn",
    false,
    "Cost",
    10000,
    "StartingEra",
    4
  }),
  PlaceObj("ApplyModifier", {
    "EnabledBy",
    "Home Deliveries",
    "Affected",
    "Residence",
    "Radius",
    20000,
    "Category",
    "Residence",
    "PropName",
    "InherentHousingQuality",
    "Description",
    T({
      5947,
      "Home Deliveries (Fast Food Joint Upgrade)"
    }),
    "Value",
    10,
    "Cap",
    20
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Smaller Packaging",
    "Name",
    T({
      5948,
      "Smaller Packaging"
    }),
    "Rollover",
    T({
      5949,
      "Halves the pollution generated by the Fast Food Joint."
    }),
    "StartTurnedOn",
    false,
    "Cost",
    5000,
    "StartingEra",
    4
  }),
  PlaceObj("ApplyModifier", {
    "EnabledBy",
    "Smaller Packaging",
    "Category",
    "Pollution",
    "PropName",
    "Amount",
    "Description",
    T({
      5950,
      "Smaller Packaging Upgrade"
    }),
    "Percent",
    true,
    "Value",
    -50
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Tourists Only",
    "Name",
    T({
      5951,
      "Tourists only"
    }),
    "Rollover",
    T({
      5563,
      "Activate to stop citizens from visiting this building (only tourists will visit). The Service Quality will increase by 10."
    }),
    "Toggle",
    true,
    "DisabledText",
    T({
      25266,
      "Deactivate to allow citizens to use the building. The Service Quality will be decreased."
    }),
    "StartTurnedOn",
    false,
    "StartingEra",
    3
  }),
  PlaceObj("ApplyModifier", {
    "EnabledBy",
    "Tourists Only",
    "PropName",
    "InherentEffectiveness",
    "Description",
    T({
      5953,
      "Tourists only"
    }),
    "Value",
    20
  })
})
