PlaceObj("BuildingTemplate", {
  "name",
  "PowerPlant",
  "file_name",
  "PowerPlant"
}, {
  PlaceObj("BuildingProperties", {
    "Model",
    "PowerPlant",
    "Flammable",
    false,
    "Name",
    T({
      6394,
      "Power Plant"
    }),
    "NamePlural",
    T({
      11666,
      "Power Plants"
    }),
    "Description",
    T({
      6395,
      "While in most parts of the world electricity is considered a necessity, in Tropico it is a precious luxury. People with access to electricity savor it like the fine delicacy it is and tell stories to their grandchildren about the time when they touched a live wire or saw a glowing light bulb. Indeed, if it was readily available for everyone, most will probably be nostalgic about the good old times when pearls were not given to the swine."
    }),
    "MenuText",
    T({
      6396,
      "Produces Electricity from Coal and Natural Gas. Consumers with higher budget are serviced preferentially."
    }),
    "Overlay",
    "Electricity",
    "BaseBudgetMin",
    100,
    "BaseBudgetMax",
    210,
    "input_pile",
    "ResourceContainersOre",
    "asphalt_road",
    true,
    "attach_preset",
    "PowerPlant",
    "TerrainName",
    "square2",
    "AmbientSound",
    "powerplant_work_sound"
  }),
  PlaceObj("ProductionPower", {
    "InputResource",
    "Coal",
    "BaseInputAmount",
    150,
    "InputCapacity",
    3000,
    "BasePowerAmount",
    4000
  }),
  PlaceObj("Construction", {
    "Research",
    "5.5. Power Plant",
    "Category",
    "infrastructure",
    "Position",
    5,
    "ConstructionCost",
    12000,
    "ConstructionPoints",
    1100,
    "Era",
    2
  }),
  PlaceObj("Pollution", {
    "BaseAmount",
    50,
    "Radius",
    20000
  }),
  PlaceObj("PowerDistributor", nil),
  PlaceObj("StandingComponent", {
    "Type",
    "environmentalists",
    "Amount",
    -10
  }),
  PlaceObj("Workplace", {
    "BaseMaxWorkers",
    6,
    "BaseInherentEducationRequired",
    4,
    "BaseInherentWealthProvided",
    4,
    "BaseInherentJobQuality",
    60,
    "Manageable",
    true,
    "WorkerProfession",
    "Engineer"
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Safe Work Environment",
    "Name",
    T({
      6397,
      "Central Air Conditioning"
    }),
    "Rollover",
    T({
      6398,
      "Job Quality is increased by 20."
    }),
    "StartTurnedOn",
    false,
    "Cost",
    4000,
    "StartingEra",
    3
  }),
  PlaceObj("ApplyModifier", {
    "EnabledBy",
    "Safe Work Environment",
    "Category",
    "Workplace",
    "PropName",
    "InherentJobQuality",
    "Description",
    T({
      6399,
      "Central Air Conditioning Upgrade"
    }),
    "Value",
    20
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Gas Turbines",
    "Name",
    T({
      6400,
      "Gas Turbines"
    }),
    "Rollover",
    T({
      6401,
      "The Power Station begins to consume Natural Gas instead of Coal. Halves the amount of pollution generated by the power station."
    }),
    "StartTurnedOn",
    false,
    "Cost",
    6000,
    "StartingEra",
    3
  }),
  PlaceObj("ProductionPower", {
    "EnabledBy",
    "Gas Turbines",
    "InputResource",
    "NaturalGas",
    "BaseInputAmount",
    100,
    "InputCapacity",
    2000,
    "BasePowerAmount",
    500
  }),
  PlaceObj("Upgrade", {
    "Id",
    "Pollution Filter",
    "Name",
    T({
      6402,
      "Pollution Filter"
    }),
    "Rollover",
    T({
      6403,
      "Reduces the amount of pollution generated by the Power Station by 25%."
    }),
    "StartTurnedOn",
    false,
    "Cost",
    5000,
    "StartingEra",
    3
  }),
  PlaceObj("ApplyModifier", {
    "EnabledBy",
    "Pollution Filter",
    "Category",
    "Pollution",
    "PropName",
    "Amount",
    "Description",
    T({
      6404,
      "Pollution Filter Upgrade"
    }),
    "Percent",
    true,
    "Value",
    -25
  })
})
